# Generated by Django 6.0.4 on 2026-04-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the loan product (e.g., Home Loan, Personal Loan)', max_length=100)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate in % (e.g., 8.50)', max_digits=5)),
                ('max_tenure_years', models.PositiveIntegerField(help_text='Maximum allowed loan tenure in years')),
                ('min_income_required', models.DecimalField(decimal_places=2, help_text='Minimum monthly income required to be eligible', max_digits=12)),
                ('max_dti_ratio', models.DecimalField(decimal_places=2, help_text='Maximum allowed DTI ratio in % (e.g., 50.0 for 50%)', max_digits=5)),
            ],
        ),
    ]
