# Generated by Django 6.0.4 on 2026-05-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='loan_type',
            field=models.CharField(choices=[('HOME', 'Home Loan'), ('VEHICLE', 'Vehicle Loan'), ('PERSONAL', 'Personal Loan'), ('BUSINESS', 'Business Loan'), ('EDUCATION', 'Education Loan')], default='PERSONAL', help_text='Type of the loan', max_length=20),
        ),
    ]
