# Generated by Django 6.0.4 on 2026-05-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_loanproduct_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='min_cibil_score',
            field=models.PositiveIntegerField(default=650, help_text='Minimum CIBIL score required for this loan product'),
        ),
    ]
